exercise_html_purifier:
    default_cache_serializer_path: '%kernel.cache_dir%/htmlpurifier'

    html_profiles:
        default:
            config:
                # the charset used by the original contents
                Core.Encoding: 'UTF-8'
                # Cache.SerializerPermissions: ~
                HTML.Allowed: img[src|alt|height|width],table[border|cellpadding|cellspacing|width],thead,tbody,tr,td[align|colspan|rowspan|valign], tfoot,p,h1,h2,h3,h4,h5,h6,br,div,address,center,em,strong,pre,u,em,ul,ol,li,strong,span,small,b 
                CSS.AllowedProperties: font,font-size,font-weight,font-style,text-decoration,padding-left,color,background-color,text-align',           
                # full configuration reference: http://htmlpurifier.org/live/configdoc/plain.html

# Read the https://github.com/Exercise/HTMLPurifierBundle/blob/master/README.md file
# to know how to whitelist elements

#            # whitelist attributes by tag
#            attributes: []

#            # whitelist elements by name
#            elements: []

#            # list of elements that cannot have attributes
#            blank_elements: []
