monolog:
    handlers:
        main:
            type: rotating_file
            max_files:      3
            path: "%kernel.logs_dir%/%kernel.environment%.all.log"
            level: debug
            channels: ["!event"]
        login:
            type:           rotating_file
            max_files:      15
            path:           "%kernel.logs_dir%/%kernel.environment%.auth.log"
            level:          info
            channels:       ["security"]
        main_error:
            type:           fingers_crossed
            action_level:   error
            handler:        streamed_error
        streamed_error:
            type:           rotating_file
            max_files:      15
            path:           "%kernel.logs_dir%/%kernel.environment%.error.log"
            level:          info
        main_critical:
            type:           fingers_crossed
            action_level:   critical
            handler:        grouped_critical
        grouped_critical:
            type:           group
            members:        [streamed_critical, buffered_critical]
        streamed_critical:
            type:           rotating_file
            max_files:      15
            path:           "%kernel.logs_dir%/%kernel.environment%.critical.log"
            level:          info
        buffered_critical:
            type:           buffer
            handler:        swift_critical
        swift_critical:
            type:           swift_mailer
            from_email:     info@127.0.0.1
            to_email:       yi.shen@127.0.0.1
            subject:        Une erreur critique est survenue ! (psmf)
            level:          info
        # main:
        #     type: stream
        #     path: "%kernel.logs_dir%/%kernel.environment%.log"
        #     level: debug
        #     channels: ["!event"]
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type: firephp
        #    level: info
        #chromephp:
        #    type: chromephp
        #    level: info
        # console:
        #     type: console
        #     process_psr_3_messages: false
        #     channels: ["!event", "!doctrine", "!console"]
